### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by 0o-de-lally** [chriswessels/meteor-tupperware#25]
@chriswessels  Firstly thanks for maintaining this resource. 

While trying to build for meteor I get the following error below. It seems like NPM is not rebuilding binaries for the target environment. Possibly related to this issue: https://github.com/meteor/meteor/issues/7512

Thanks in advance
/////////////////////////
/output/bundle/programs/server/node_modules/fibers/future.js:267
                        throw(ex);
                        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/output/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/output/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by chriswessels** [comment]
Hi @lpgeiger, unfortunately I'm no longer maintaining this package. If you're looking for an alternative, I'd highly recommend https://github.com/jshimko/meteor-launchpad. Thanks for using tupperware.
