### ISSUE TITLE
Builder can not write without either data or a file path or a symlink path: os/packages/packages.json

### ISSUE THREAD

**Issue by adamgins** [chriswessels/meteor-tupperware#34]
hi, thanks for the package... I am getting the following error when running the quickstart....

Any ideas pls?
BTW< I need a Meteor settings file... so expect I need to do as an ENV var  in the dockerfile?

```
# Executing 2 build triggers...
Step 1/1 : COPY ./ /app
Step 1/1 : RUN sh /tupperware/scripts/on_build.sh
 ---> Running in c2418683b864

  _                                                      
 | |_ _   _ _ __  _ __   ___ _ ____      ____ _ _ __ ___ 
 | __| | | | '_ \| '_ \ / _ \ '__\ \ /\ / / _` | '__/ _ \
 | |_| |_| | |_) | |_) |  __/ |   \ V  V / (_| | | |  __/
  \__|\__,_| .__/| .__/ \___|_|    \_/\_/ \__,_|_|  \___|
           |_|   |_|                                     

[-]  github.com/chriswessels/meteor-tupperware (tupperbuild v1.0.0)

[-]  No tupperware.json found, using defaults.
[-]  Downloading Meteor 1.5.2 Installer...
[-]  Installing Meteor 1.5.2...
[-]  Building your app...
[!]  While attempting to build your application, the command: meteor build --allow-superuser --directory /output --architecture os.linux.x86_64 
[!]  Failed with the exit code 1. The signal was null.
[-]  The task produced the following stdout:

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

buzzy-buzz:resources-core: updating npm dependencies -- aws-sdk,
s3-write-stream, webshot, vimeo-api, html-truncate...

[-]  The task produced the following stderr:
/root/.meteor/packages/templating-compiler/.1.3.2.1fkuaqr++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: Builder can not write without either data or a file path or a symlink path: os/packages/packages.json
  at Builder.write (/root/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/builder.js:322:13)
  at Builder.writeToGeneratedFilename (/root/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/builder.js:466:10)
  at /root/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/isopack.js:1357:43
```

**Comment by adamgins** [comment]
just rebuilding without `npm-container` as per https://stackoverflow.com/questions/36362116/meteor-packages-json-error-workaround-when-upgrading-from-1-2-to-1-3-and-deployi

**Comment by adamgins** [comment]
removing `npm-container` solved this issue
